sudo: required
env:
  - >
    container_id=$(mktemp)
    distribution=ubuntu
    version=16.04
    init=/sbin/init
    run_opts=""

services:
  - docker

before_install:
  - docker pull buildpack-deps:xenial-scm

script:
  - docker run -dti buildpack-deps:xenial-scm bash > "${container_id}"
  - docker exec --tty "$(cat ${container_id})"  bash -c "ssh-keyscan github.com > ~/.ssh/known_hosts"
  - docker exec --tty "$(cat ${container_id})" bash -c "$(curl -fsSL https://raw.github.com/napcae/dotfiles/master/bin/dotfiles)"
  - docker exec --tty "$(cat ${container_id})"  bash -c "source ~/.bashrc"

notifications:
  email: false
